/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TijdenRouteImport } from './routes/tijden'
import { Route as GebruikersRouteImport } from './routes/gebruikers'
import { Route as DrempelsRouteImport } from './routes/drempels'
import { Route as ClustersRouteImport } from './routes/clusters'
import { Route as IndexRouteImport } from './routes/index'

const TijdenRoute = TijdenRouteImport.update({
  id: '/tijden',
  path: '/tijden',
  getParentRoute: () => rootRouteImport,
} as any)
const GebruikersRoute = GebruikersRouteImport.update({
  id: '/gebruikers',
  path: '/gebruikers',
  getParentRoute: () => rootRouteImport,
} as any)
const DrempelsRoute = DrempelsRouteImport.update({
  id: '/drempels',
  path: '/drempels',
  getParentRoute: () => rootRouteImport,
} as any)
const ClustersRoute = ClustersRouteImport.update({
  id: '/clusters',
  path: '/clusters',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clusters': typeof ClustersRoute
  '/drempels': typeof DrempelsRoute
  '/gebruikers': typeof GebruikersRoute
  '/tijden': typeof TijdenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clusters': typeof ClustersRoute
  '/drempels': typeof DrempelsRoute
  '/gebruikers': typeof GebruikersRoute
  '/tijden': typeof TijdenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clusters': typeof ClustersRoute
  '/drempels': typeof DrempelsRoute
  '/gebruikers': typeof GebruikersRoute
  '/tijden': typeof TijdenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/clusters' | '/drempels' | '/gebruikers' | '/tijden'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/clusters' | '/drempels' | '/gebruikers' | '/tijden'
  id: '__root__' | '/' | '/clusters' | '/drempels' | '/gebruikers' | '/tijden'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClustersRoute: typeof ClustersRoute
  DrempelsRoute: typeof DrempelsRoute
  GebruikersRoute: typeof GebruikersRoute
  TijdenRoute: typeof TijdenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tijden': {
      id: '/tijden'
      path: '/tijden'
      fullPath: '/tijden'
      preLoaderRoute: typeof TijdenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gebruikers': {
      id: '/gebruikers'
      path: '/gebruikers'
      fullPath: '/gebruikers'
      preLoaderRoute: typeof GebruikersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drempels': {
      id: '/drempels'
      path: '/drempels'
      fullPath: '/drempels'
      preLoaderRoute: typeof DrempelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clusters': {
      id: '/clusters'
      path: '/clusters'
      fullPath: '/clusters'
      preLoaderRoute: typeof ClustersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClustersRoute: ClustersRoute,
  DrempelsRoute: DrempelsRoute,
  GebruikersRoute: GebruikersRoute,
  TijdenRoute: TijdenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
